[package]
name = "tree-sitter-GAP"
description = "GAP grammar for the tree-sitter parsing library"
version = "0.1.0"
keywords = ["incremental", "parsing", "GAP", "GAP-system"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/reiniscirpons/tree-sitter-GAP"
edition = "2024"
license = "MIT"

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = "0.19.3"

[build-dependencies]
cc = "1.0"
