name: CI

on:
  push:
    branches: [master]
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
  pull_request:
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v2
      - name: Set up examples
        run: |-
          git clone --single-branch --depth=1 --filter=blob:none https://github.com/gap-system/gap examples/gap
          git clone --single-branch --depth=1 --filter=blob:none https://github.com/semigroups/Semigroups examples/semigroups
          git clone --single-branch --depth=1 --filter=blob:none https://github.com/digraphs/Digraphs examples/digraphs
      - name: Run tests
        uses: tree-sitter/parser-test-action@v3
        with:
          # Uncomment tests as they get fixed
          test-rust: true
          # test-node: true
          test-python: true
          test-go: true
          test-swift: true
      - name: Parse examples
        uses: tree-sitter/parse-action@v4
        with:
          files: |
            examples/**/*.g
            examples/**/*.gi
            examples/**/*.gd
          # invalid-files: |
          # example-invalid-file.g No invalid files yet
  
  query:
    name: Validate queries
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v5

      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v2

      - name: Build parser
        run: tree-sitter build

      - name: Set up ts_query_ls
        run: curl -fL https://github.com/ribru17/ts_query_ls/releases/latest/download/ts_query_ls-x86_64-unknown-linux-gnu.tar.gz | tar -xz

      - name: Check queries
        run: ./ts_query_ls check -f queries
